const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){let clock=1000;const writes=[],elements={'#closePages':{},'#timer':{},'#timerStatus':{}};const ctx=vm.createContext({supabase:{createClient:()=>({})},TQ_CONFIG:{},TQModel:require('../web/model.js'),document:{hidden:false,querySelector:s=>elements[s]||null,addEventListener(){}},window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:false}),crypto:{randomUUID:()=> 'device'},Date:class extends Date{static now(){return clock}},setInterval:()=>1,clearInterval(){},setTimeout(){},clearTimeout(){},console});vm.runInContext(fs.readFileSync('web/app.js','utf8').replace(/boot\(\);\s*$/,''),ctx);vm.runInContext("user={id:'user'};timerReady=true;lastActivity=Date.now();record=async(kind,payload,id)=>{writes.push({kind,payload,id});};",Object.assign(ctx,{writes}));return {ctx,writes,setClock:n=>clock=n,run:s=>vm.runInContext(s,ctx)};}
test('opens automatically, stays global across navigation, stops at 4 minutes and resumes',async()=>{const t=setup();await t.run('timerPulse()');assert.equal(t.writes[0].payload.action,'start');assert.equal(t.writes[0].id,null);t.setClock(21000);await t.run("route='history';unit={id:'different'};timerPulse()");assert.equal(t.writes.at(-1).payload.action,'tick');assert.equal(t.writes.at(-1).id,null);t.setClock(241000);await t.run('timerPulse()');assert.equal(t.writes.at(-1).payload.action,'stop');assert.equal(t.run('timing'),false);t.setClock(250000);t.run('activity()');await t.run('timerQueue');assert.equal(t.writes.at(-1).payload.action,'start');});
test('hidden page pauses and other device lease failure retries without counting',async()=>{const t=setup();await t.run('timerPulse()');await t.run('document.hidden=true;timerPulse()');assert.equal(t.writes.at(-1).payload.action,'stop');t.run("document.hidden=false;record=async()=>{throw Error('lease')}");await t.run('timerPulse()');assert.equal(t.run('timing'),false);assert.equal(t.run('nextTimerRetry'),46000);});

test('reading position selects newest account-local or cloud record and restores offset',async()=>{const t=setup();t.run("localStorage.getItem=()=>JSON.stringify({unitId:'old',scrollY:50,updatedAt:10});state.settings.lastReading={unitId:'new',scrollY:900,updatedAt:20};catalog=[{id:'new',ready:true}];openUnit=async(id,p)=>{writes.push({id,p})};");await t.run('restoreReading()');assert.equal(t.writes[0].id,'new');assert.equal(t.writes[0].p.scrollY,900);t.run("localStorage.getItem=()=>JSON.stringify({unitId:'new',scrollY:1200,updatedAt:30})");assert.equal(t.run('savedReading().scrollY'),1200);});
test('reading position is saved locally before the delayed cloud write',()=>{const t=setup();t.run("route='reader';unit={id:'p'};window.scrollY=420;localStorage.setItem=(key,value)=>writes.push({key,value});saveReading();");assert.equal(t.writes[0].key,'tq-last-reading-user');assert.equal(JSON.parse(t.writes[0].value).scrollY,420);});

test('mobile directory closes without selecting a unit and hides the backdrop',()=>{const t=setup();t.run("matchMedia=()=>({matches:true});const nodes={};document.querySelector=s=>nodes[s]??=({classList:{toggle(){}},setAttribute(){}});sidebarHidden=false;applySidebar();setSidebar(true);");assert.equal(t.run('sidebarHidden'),true);assert.equal(t.run("document.querySelector('#navBackdrop').hidden"),true);assert.equal(t.run('unit'),undefined);});
