'use strict';
const db=supabase.createClient(TQ_CONFIG.url,TQ_CONFIG.publishableKey),M=TQModel,$=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user,catalog=[],events=[],state=M.reduce([]),siteSettings={},route='home',unit,content,timing=false,timerBusy=false,syncBusy=false,timerHandle,device=crypto.randomUUID(),pending=[],clockOffset=0;
const duration=s=>Math.floor((s||0)/60)+' 分 '+String((s||0)%60).padStart(2,'0')+' 秒';
const draftKey=()=>user&&unit?'tq-draft-'+user.id+'-'+unit.id:null;
const noteText=u=>sessionStorage.getItem(draftKey())??u.notes?.at(-1)?.text??'';
const now=()=>Date.now()+clockOffset;
const toast=m=>{$('#toast').textContent=m;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000);};
const check=r=>{if(r.error)throw r.error;return r.data;};
function prefs(){const p=state.settings;document.body.classList.toggle('dark',p.theme==='dark');document.documentElement.style.setProperty('--font',(p.font||18)+'px');document.documentElement.style.setProperty('--width',(p.width||780)+'px');}
function storePending(){for(const e of pending)localStorage.setItem('tq-event-'+user.id+'-'+e.id,JSON.stringify(e));}
function readPending(){const prefix='tq-event-'+user.id+'-';return Object.keys(localStorage).filter(k=>k.startsWith(prefix)).map(k=>JSON.parse(localStorage.getItem(k)));}
async function pull(){let rows=[],after=0;while(true){const data=check(await db.from('tq_events').select('*').gt('seq',after).order('seq').limit(1000));rows.push(...data);if(data.length<1000)break;after=data.at(-1).seq;}events=rows;state=M.reduce([...events,...pending]);prefs();if(route==='reader'&&unit&&$('#status')&&document.activeElement!==$('#status'))$('#status').value=state.units[unit.id]?.status||'未学习';if($('#timer'))$('#timer').textContent=duration(state.units[unit?.id]?.seconds);}
async function sync(){if(!user||syncBusy)return;syncBusy=true;pending=readPending();try{for(const e of [...pending]){const r=await db.from('tq_events').insert({id:e.id,user_id:user.id,unit_id:e.unit_id,kind:e.kind,payload:e.payload});if(r.error&&r.error.code!=='23505')throw r.error;localStorage.removeItem('tq-event-'+user.id+'-'+e.id);pending=pending.filter(p=>p.id!==e.id);storePending();}await pull();if($('#sync'))$('#sync').textContent=pending.length?'待同步 '+pending.length+' 项':'已同步';if(route==='home'||route==='review')render();}catch(e){if($('#sync'))$('#sync').textContent=pending.length?'待同步 '+pending.length+' 项':'连接中断';}finally{syncBusy=false;}}
async function record(kind,payload,unitId=unit?.id){const e={id:crypto.randomUUID(),user_id:user.id,unit_id:unitId||null,kind,payload,created_at:new Date(now()).toISOString()};if(['time','plan','answer'].includes(kind)){check(await db.from('tq_events').insert({id:e.id,user_id:e.user_id,unit_id:e.unit_id,kind,payload}));await pull();}else{pending.push(e);storePending();state=M.reduce([...events,...pending]);await sync();}}
async function boot(){try{const r=check(await db.auth.getUser());user=r.user;}catch{}if(!user){login();return;}try{const member=check(await db.from('tq_members').select('user_id').eq('user_id',user.id).maybeSingle());if(!member){$('#app').innerHTML='<div class="login"><h1>此账号尚未获授权</h1><p>教材仅对私人学习账号开放。</p><button id="out">退出登录</button></div>';$('#out').onclick=logout;return;}pending=readPending();catalog=check(await db.from('tq_catalog').select('*').order('sort_order'));const settings=check(await db.from('tq_site_settings').select('key,value'));siteSettings=Object.fromEntries(settings.map(x=>[x.key,x.value]));const clock=await db.rpc('tq_clock');if(!clock.error)clockOffset=new Date(clock.data).getTime()-Date.now();await pull();await ensurePlan();render();sync();}catch(e){$('#app').innerHTML='<div class="login"><h1>暂时无法加载</h1><p>'+esc(e.message)+'</p><button onclick="location.reload()">重试</button></div>';}}
function login(){$('#app').innerHTML='<form class="login" id="login"><div class="eyebrow">2027 · 私人学习空间</div><h1>教育知识与能力</h1><p class="muted">每天一点，稳步准备高中数学教资。</p><label>邮箱<input name="email" type="email" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">登录并同步</button><p id="error" role="alert"></p><small>请使用已获授权的 Supabase 学习账号。登录后才能读取教材。</small></form>';$('#login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{check(await db.auth.signInWithPassword({email:e.target.email.value,password:e.target.password.value}));await boot();}catch(err){$('#error').textContent=err.message;}finally{b.disabled=false;}};}
async function logout(){await stopTimer();await sync();check(await db.auth.signOut());user=null;events=[];catalog=[];content=null;unit=null;siteSettings={};$('#pages').close();$('#pageImage').innerHTML='';login();}
async function ensurePlan(){const d=M.day(now());if(!state.days[d]?.plan&&catalog.some(c=>c.ready&&c.kind==='point')){try{await record('plan',{day:d},null);}catch(e){if(e.code!=='23505')throw e;await pull();}}}
function links(items){return items.map(c=>'<button data-unit="'+esc(c.id)+'">'+esc(c.title)+(c.ready?'':' · 整理中')+'</button>').join('');}
function render(){prefs();$('#app').innerHTML='<aside class="sidebar"><div class="brand">2027 教资<small>科目二 · 教育知识与能力</small></div><nav class="nav">'+[['home','今日学习'],['review','复习与错题'],['saved','收藏与笔记'],['history','学习记录'],['settings','阅读设置']].map(([v,t])=>'<button data-route="'+v+'" class="'+(route===v?'selected':'')+'">'+t+'</button>').join('')+'</nav><div class="catalog">'+catalog.filter(c=>c.kind==='chapter').map(c=>'<details '+(c.id==='c1'?'open':'')+'><summary>'+esc(c.title)+'</summary>'+catalog.filter(s=>s.parent_id===c.id).map(s=>'<div class="section-title">'+esc(s.title)+'</div>'+links(catalog.filter(p=>p.parent_id===s.id))).join('')+'</details>').join('')+'</div></aside><main class="main"><header class="topbar"><button class="mobile-menu" id="menu">目录</button><span class="title-label">我的学习空间<small id="sync">'+(pending.length?'待同步 '+pending.length+' 项':'已同步')+'</small></span><div class="top-actions"><span class="timer" id="timer">'+duration(state.units[unit?.id]?.seconds)+'</span><button id="timerBtn" '+(!unit?'disabled':'')+'>'+(timing?'暂停计时':'开始计时')+'</button><button id="out">退出</button></div></header><div class="body" id="body"></div></main>';
  $('#out').onclick=logout;$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#timerBtn').onclick=()=>timing?stopTimer():startTimer();document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{await stopTimer();route=b.dataset.route;render();});document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.unit));if(route==='reader')reader();else if(route==='home')home();else if(route==='settings')settings();else listView();
}
function examCountdown(){const cfg=siteSettings.exam_date||{},date=cfg.date;if(!date)return '<div class="countdown pending"><small>2027年上半年高中数学教资笔试</small><strong>官方日期待公布</strong><span>公布后由后台更新，网站会自动显示剩余天数</span></div>';const target=new Date(date+'T00:00:00+08:00').getTime(),days=Math.max(0,Math.ceil((target-now())/86400000));return '<div class="countdown"><small>距离2027年上半年高中数学教资笔试</small><strong>'+days+' 天</strong><span>'+esc(date)+(cfg.official?' · 官方日期':' · 暂定日期')+'</span></div>';}
function home(){const d=M.day(now()),daily=state.days[d]||{seconds:0},plan=daily.plan,goal=plan?.goal||1500;let streak=0;for(let i=0;i<365;i++){const x=state.days[M.day(now()-i*86400000)];if(i===0&&(!x?.plan||x.seconds<x.plan.goal))continue;if(!x?.plan||x.seconds<x.plan.goal)break;streak++;}const n=new Date(now()+8*3600000).getUTCDay()||7,week=Array.from({length:n},(_,i)=>M.day(now()-(n-1-i)*86400000)),done=week.filter(k=>state.days[k]?.plan&&state.days[k].seconds>=state.days[k].plan.goal).length;$('#body').innerHTML='<div class="welcome"><div><div class="eyebrow">'+d+'</div><h1>今天，也向前一步。</h1><p class="muted">先完成今天的任务，再决定是否继续。</p></div><span class="tag">第一章精校版</span></div>'+examCountdown()+'<div class="stats">'+[['今日学习',duration(daily.seconds)],['今日目标',goal/60+' 分钟'],['连续达标',streak+' 天'],['本周完成率',Math.round(done/week.length*100)+'%']].map(([a,b])=>'<div class="card stat"><small>'+a+'</small><strong>'+b+'</strong></div>').join('')+'</div><div class="dashboard-grid"><section class="card"><h2>今日任务</h2><div class="bar"><span style="width:'+Math.min(100,daily.seconds/goal*100)+'%"></span></div>'+(plan?.replanned?'<p class="warning">连续三天未达标，今天减至10分钟、一个知识点。历史记录保留。</p>':'')+(plan?.point_ids||[]).map(id=>{const c=catalog.find(c=>c.id===id);return c?'<div class="task"><div>'+esc(c.title)+'<p class="muted">'+esc(state.units[id]?.status||'未学习')+'</p></div><button data-open="'+id+'">开始学习</button></div>':'';}).join('')+(!plan?'<p class="empty">今日任务正在生成。</p>':'')+'</section><section class="card"><h2>本周记录</h2><p class="muted">以北京时间和服务器计时为准，未完成记录不会补签或清除。</p>'+week.map(k=>'<div class="history-row"><span>'+k+'</span><span>'+(state.days[k]?.seconds>=(state.days[k]?.plan?.goal||Infinity)?'已达标':'未达标')+'</span></div>').join('')+'</section></div>';bindOpen();}
function bindOpen(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openUnit(b.dataset.open));}
async function openUnit(id){await stopTimer();unit=catalog.find(c=>c.id===id);if(!unit?.ready){toast('该知识点尚在整理');return;}try{content=check(await db.from('tq_content').select('*').eq('id',id).single());route='reader';render();window.scrollTo(0,0);}catch(e){toast(e.message);}}
function highlighted(text,u){let html=esc(text);for(const h of u.highlights||[]){const safe=esc(h);if(safe&&html.includes(safe))html=html.split(safe).join('<mark>'+safe+'</mark>');}return html;}
function richItem(item,u){const text=highlighted(item.text||'',u);if(item.type==='table')return '<div class="table-wrap"><table><caption>'+esc(item.caption||'教材表格')+'</caption><thead><tr>'+item.headers.map(h=>'<th>'+highlighted(h,u)+'</th>').join('')+'</tr></thead><tbody>'+item.rows.map(r=>'<tr>'+r.map(c=>'<td>'+highlighted(c,u).replaceAll('\n','<br>')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';if(item.type==='h2')return '<h3 class="source-h2">'+text+'</h3>';if(item.type==='h3')return '<h4 class="source-h3">'+text+'</h4>';if(item.type==='h4')return '<h5 class="source-h4">'+text+'</h5>';if(item.type==='callout')return '<div class="source-callout">'+text+'</div>';if(item.type==='list')return '<p class="source-list">'+text+'</p>';if(item.type==='option')return '<div class="source-option">'+text+'</div>';if(item.type==='figure-note')return '<figure class="figure-note"><blockquote>'+text+'</blockquote><figcaption>'+esc(item.caption)+'</figcaption></figure>';return '<p>'+text+'</p>';}
function sourceBlock(block,u){if(block.type!=='page')return '';return '<section class="source-page" data-pdf="'+block.pdf_page+'"><div class="page-label"><span>教材第 '+block.page+' 页</span><button data-page="'+block.pdf_page+'">查看原页</button></div>'+block.items.map(x=>richItem(x,u)).join('')+'</section>';}
function aiSection(title,key){return '<section class="ai-section"><h2>'+title+' <span>AI辅助</span></h2><div class="ai-panel"><p>'+esc(content[key]||'待补充。')+'</p></div></section>';}
function lastAttempt(u,qid){return (u.attempts||[]).filter(a=>a.question_id===qid).at(-1);}
function questionHtml(q,i,u){const a=lastAttempt(u,q.id),typeName={choice:'选择题',judgement:'辨析题',short:'简答题',material:'材料分析题'}[q.type]||q.type;let body='';if(q.type==='choice'||q.type==='judgement'){body='<div class="options">'+q.options.map((o,n)=>{const value=q.type==='choice'?String.fromCharCode(65+n):o;return '<label><input type="radio" name="q-'+i+'" value="'+esc(value)+'"> <span>'+esc(q.type==='choice'?value+'. '+o:o)+'</span></label>';}).join('')+'</div><button class="primary" data-objective="'+i+'">提交答案</button>';}else{body='<textarea class="answer-input" data-response="'+i+'" placeholder="请先写出答案，再按评分要点核对"></textarea><details class="rubric"><summary>查看评分要点</summary><p>'+esc(q.rubric||q.answer)+'</p></details><div class="row"><button data-subjective="'+i+'" data-correct="true">达到主要评分点</button><button data-subjective="'+i+'" data-correct="false">需要复习</button></div>';}return '<div class="question"><div class="question-meta"><span>'+esc(q.label||'AI生成练习')+'</span><b>'+typeName+'</b></div><p>'+esc(q.prompt)+'</p>'+body+(a?'<div class="attempt '+(a.correct?'ok':'bad')+'">最近一次：'+(a.correct?'正确/达标':'错误/需复习')+(a.response?' · 作答：'+esc(a.response):'')+'</div>':'')+'</div>';}
function pageRange(){return unit.page_start===unit.page_end?'教材第 '+unit.page_start+' 页':'教材第 '+unit.page_start+'—'+unit.page_end+' 页';}
function nextReadyUnit(){const ready=catalog.filter(c=>c.kind==='point'&&c.ready);return ready[ready.findIndex(c=>c.id===unit.id)+1];}
function reader(){const u=state.units[unit.id]||{status:'未学习',notes:[],highlights:[],attempts:[]},next=nextReadyUnit(),nextNav=next?'<nav class="next-unit" aria-label="继续学习"><div><small>下一个知识点</small><strong>'+esc(next.title)+'</strong></div><button class="primary" id="nextUnit">进入下一个知识点</button></nav>':'<nav class="next-unit chapter-done" aria-label="本章完成"><div><small>第一章已到末尾</small><strong>完成后可回到今日任务继续复习</strong></div><button class="primary" id="backHome">返回今日学习</button></nav>';$('#body').innerHTML='<article class="reader"><div class="read-head"><div class="eyebrow">'+pageRange()+'</div><h1>'+esc(unit.title)+'</h1><div class="row"><button id="mode">切换冲刺模式</button><button id="scan">查看教材原页</button><button id="bookmark">'+(u.bookmark?'取消收藏':'收藏')+'</button><button id="highlight">高亮选中文字</button></div><div class="row"><label>学习状态 <select id="status">'+['未学习','学习中','模糊','已掌握'].map(x=>'<option '+(u.status===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><small>错误 '+(u.wrong||0)+' 次 · 自测正确率 '+(u.answers?Math.round(u.correct/u.answers*100):0)+'% · 下次复习 '+(u.due?M.day(u.due):'完成自测后安排')+'</small></div></div><p class="verification">'+esc(content.verification)+' 扫描原页始终是最高优先级依据。</p><section class="source-section"><h2>教材原文</h2><div class="source">'+content.blocks.map(b=>sourceBlock(b,u)).join('')+'</div></section>'+aiSection('AI辅助解释','explanation')+aiSection('考试重点','exam')+aiSection('易错点','pitfalls')+'<section><h2>个人笔记</h2><textarea id="note" aria-label="个人笔记" placeholder="写下自己的理解，每次保存保留一个版本">'+esc(noteText(u))+'</textarea><button id="saveNote">保存笔记</button><details class="versions"><summary>历史版本（'+(u.notes?.length||0)+'）</summary>'+(u.notes||[]).slice().reverse().map(n=>'<p><small>'+esc(n.at)+'</small><br>'+esc(n.text)+'</p>').join('')+'</details></section><section><h2>自测题 <span class="ai-label">AI生成练习</span></h2><p class="muted">选择题与辨析题自动评分；简答题和材料分析题需先书面作答，再对照评分点自评。</p>'+content.questions.map((q,i)=>questionHtml(q,i,u)).join('')+'</section>'+nextNav+'</article>';
  $('#mode').onclick=()=>{$('.reader').classList.toggle('sprint');$('#mode').textContent=$('.reader').classList.contains('sprint')?'切换教材模式':'切换冲刺模式';};$('#scan').onclick=()=>showPage(unit.page_start+4);$('#bookmark').onclick=async()=>{await record('bookmark',{value:!u.bookmark});reader();};$('#status').onchange=async e=>{await record('status',{value:e.target.value});toast('状态已保存');};$('#note').oninput=()=>sessionStorage.setItem(draftKey(),$('#note').value);$('#saveNote').onclick=async()=>{const key=draftKey(),text=$('#note').value;await record('note',{text});if($('#note')?.value===text)sessionStorage.removeItem(key);toast(pending.length?'笔记已保存在本机，等待同步':'笔记已同步，旧版本保留');reader();};$('#highlight').onclick=async()=>{const sel=window.getSelection(),txt=sel.toString().trim();if(!txt||!$('.source').contains(sel.anchorNode)){toast('请先选择教材原文中的文字');return;}await record('highlight',{text:txt});reader();};if(next)$('#nextUnit').onclick=()=>openUnit(next.id);else $('#backHome').onclick=async()=>{await stopTimer();unit=null;content=null;route='home';render();window.scrollTo(0,0);};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(+b.dataset.page));document.querySelectorAll('[data-objective]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.objective,q=content.questions[i],chosen=document.querySelector('input[name="q-'+i+'"]:checked');if(!chosen){toast('请先选择答案');return;}b.disabled=true;try{await record('answer',{question_id:q.id,response:chosen.value});toast('已评分并更新复习时间');reader();}catch(e){toast(e.message);b.disabled=false;}});document.querySelectorAll('[data-subjective]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.subjective,q=content.questions[i],input=document.querySelector('[data-response="'+i+'"]'),response=input.value.trim();if(response.length<5){toast('请先写出答案，再对照评分要点');return;}b.disabled=true;try{await record('answer',{question_id:q.id,response,correct:b.dataset.correct==='true'});toast('作答已记录并更新复习时间');reader();}catch(e){toast(e.message);b.disabled=false;}});
}
async function loadScan(n,el){try{const p=check(await db.from('tq_pages').select('image_data').eq('pdf_page',n).single());const img=new Image();img.alt='教材扫描第 '+n+' 页';img.src=p.image_data;el.replaceChildren(img);}catch{el.textContent='原页暂未载入，请稍后重试。';}}
async function showPage(n){$('#pageControls').innerHTML='<button id="prevPage" '+(n<=unit.page_start+4?'disabled':'')+'>上一页</button><span>扫描 '+n+' / 教材 '+(n-4)+'</span><button id="nextPage" '+(n>=unit.page_end+4?'disabled':'')+'>下一页</button>';$('#prevPage').onclick=()=>showPage(n-1);$('#nextPage').onclick=()=>showPage(n+1);$('#pageImage').textContent='正在加载…';if(!$('#pages').open)$('#pages').showModal();await loadScan(n,$('#pageImage'));}
$('#closePages').onclick=()=>$('#pages').close();
function settings(){$('#body').innerHTML='<section class="card settings"><h1>阅读设置</h1><label>主题<select id="theme"><option value="light">浅色</option><option value="dark">深色</option></select></label><label>字体大小<input id="font" type="range" min="16" max="28" value="'+(state.settings.font||18)+'"></label><label>阅读宽度<input id="width" type="range" min="600" max="1100" step="20" value="'+(state.settings.width||780)+'"></label><p class="muted">设置会同步到其他设备。考试日期由后台依据官方公告统一更新。</p></section>';$('#theme').value=state.settings.theme||'light';for(const id of ['theme','font','width'])$('#'+id).onchange=async e=>{await record('settings',{[id]:id==='theme'?e.target.value:+e.target.value},null);prefs();};}
function listView(){if(route==='history'){$('#body').innerHTML='<section class="card"><h1>学习记录</h1>'+Object.entries(state.days).sort().reverse().map(([d,v])=>'<div class="history-row"><span>'+d+'</span><span>'+duration(v.seconds)+' · '+(v.plan&&v.seconds>=v.plan.goal?'已达标':'未达标')+'</span></div>').join('')+'</section>';return;}const rows=catalog.filter(c=>c.kind==='point'&&(route==='saved'?(state.units[c.id]?.bookmark||state.units[c.id]?.notes?.length):(state.units[c.id]?.lastCorrect===false||state.units[c.id]?.status==='模糊'||(state.units[c.id]?.due&&new Date(state.units[c.id].due).getTime()<=now()))));$('#body').innerHTML='<section class="card"><h1>'+(route==='saved'?'收藏与笔记':'复习与错题')+'</h1>'+rows.map(c=>{const u=state.units[c.id]||{};return '<div class="task"><span>'+esc(c.title)+(route==='review'?' <small>错误 '+(u.wrong||0)+' 次</small>':'')+'</span><button data-open="'+c.id+'">打开</button></div>';}).join('')+(!rows.length?'<p class="empty">这里暂时没有记录。</p>':'')+'</section>';bindOpen();}
async function startTimer(){if(timing||timerBusy||!unit)return;timerBusy=true;try{await record('time',{action:'start',device});timing=true;timerHandle=setInterval(tick,20000);if($('#timerBtn'))$('#timerBtn').textContent='暂停计时';}catch(e){toast(e.message);}finally{timerBusy=false;}}
async function tick(){if(!timing||timerBusy)return;timerBusy=true;try{await record('time',{action:'tick',device});if($('#timer'))$('#timer').textContent=duration(state.units[unit.id]?.seconds);}catch(e){clearInterval(timerHandle);timing=false;toast('计时连接中断，请重新开始');if($('#timerBtn'))$('#timerBtn').textContent='开始计时';}finally{timerBusy=false;}}
async function stopTimer(){if(!timing)return;clearInterval(timerHandle);timing=false;try{await record('time',{action:'stop',device});}catch(e){toast('计时已停止，未确认的时长不计入达标');}if($('#timerBtn'))$('#timerBtn').textContent='开始计时';if($('#timer'))$('#timer').textContent=duration(state.units[unit?.id]?.seconds);}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTimer();else{sync();ensurePlan().catch(()=>{});}});window.addEventListener('online',sync);window.addEventListener('storage',e=>{if(user&&e.key?.startsWith('tq-event-'+user.id+'-'))sync();});setInterval(()=>{if(user&&!document.hidden)sync();},15000);boot();
