'use strict';
const db=supabase.createClient(TQ_CONFIG.url,TQ_CONFIG.publishableKey),M=TQModel,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user,catalog=[],events=[],state=M.reduce([]),route='home',unit,content,timing=false,timerBusy=false,syncBusy=false,timerHandle,device=crypto.randomUUID(),pending=[],clockOffset=0;
const now=()=>Date.now()+clockOffset,toast=m=>{$('#toast').textContent=m;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000);},check=r=>{if(r.error)throw r.error;return r.data;};
function prefs(){const p=state.settings;document.body.classList.toggle('dark',p.theme==='dark');document.documentElement.style.setProperty('--font',(p.font||18)+'px');document.documentElement.style.setProperty('--width',(p.width||780)+'px');}
function storePending(){for(const e of pending)localStorage.setItem('tq-event-'+user.id+'-'+e.id,JSON.stringify(e));}
function readPending(){const prefix='tq-event-'+user.id+'-';return Object.keys(localStorage).filter(k=>k.startsWith(prefix)).map(k=>JSON.parse(localStorage.getItem(k)));}
async function pull(){let rows=[],after=0;while(true){const data=check(await db.from('tq_events').select('*').gt('seq',after).order('seq').limit(1000));rows.push(...data);if(data.length<1000)break;after=data.at(-1).seq;}events=rows;state=M.reduce([...events,...pending]);prefs();}
async function sync(){if(!user||syncBusy)return;syncBusy=true;pending=readPending();try{for(const e of [...pending]){const r=await db.from('tq_events').insert({id:e.id,user_id:user.id,unit_id:e.unit_id,kind:e.kind,payload:e.payload});if(r.error&&r.error.code!=='23505')throw r.error;localStorage.removeItem('tq-event-'+user.id+'-'+e.id);pending=pending.filter(p=>p.id!==e.id);storePending();}await pull();if($('#sync'))$('#sync').textContent='已同步';if(route==='home')render();}catch(e){if($('#sync'))$('#sync').textContent=pending.length?'待同步 '+pending.length+' 项':'连接中断';}finally{syncBusy=false;}}
async function record(kind,payload,unitId=unit?.id){const e={id:crypto.randomUUID(),user_id:user.id,unit_id:unitId||null,kind,payload,created_at:new Date(now()).toISOString()};if(['time','plan'].includes(kind)){check(await db.from('tq_events').insert({id:e.id,user_id:e.user_id,unit_id:e.unit_id,kind,payload}));await pull();}else{pending.push(e);storePending();state=M.reduce([...events,...pending]);await sync();}}
async function boot(){try{const r=check(await db.auth.getUser());user=r.user;}catch{}if(!user){login();return;}try{const member=check(await db.from('tq_members').select('user_id').eq('user_id',user.id).maybeSingle());if(!member){$('#app').innerHTML='<div class="login"><h1>此账号尚未获授权</h1><p>教材仅对私人学习账号开放。</p><button id="out">退出登录</button></div>';$('#out').onclick=logout;return;}pending=readPending();catalog=check(await db.from('tq_catalog').select('*').order('sort_order'));const clock=await db.rpc('tq_clock');if(!clock.error)clockOffset=new Date(clock.data).getTime()-Date.now();await pull();await ensurePlan();render();sync();}catch(e){$('#app').innerHTML='<div class="login"><h1>暂时无法加载</h1><p>'+esc(e.message)+'</p><button onclick="location.reload()">重试</button></div>';}}
function login(){$('#app').innerHTML='<form class="login" id="login"><div class="eyebrow">2027 · 私人学习空间</div><h1>教育知识与能力</h1><p class="muted">每天一点，稳步准备高中数学教资。</p><label>邮箱<input name="email" type="email" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">登录并同步</button><p id="error" role="alert"></p><small>请使用已获授权的 Supabase 学习账号。登录后才能读取教材。</small></form>';$('#login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{check(await db.auth.signInWithPassword({email:e.target.email.value,password:e.target.password.value}));await boot();}catch(err){$('#error').textContent=err.message;}finally{b.disabled=false;}};}
async function logout(){await stopTimer();await sync();check(await db.auth.signOut());user=null;events=[];catalog=[];content=null;unit=null;$('#pages').close();$('#pageImage').innerHTML='';login();}
async function ensurePlan(){const d=M.day(now());if(!state.days[d]?.plan&&catalog.some(c=>c.ready&&c.kind==='point')){try{await record('plan',{day:d},null);}catch(e){if(e.code!=='23505')throw e;await pull();}}}
function links(items){return items.map(c=>'<button data-unit="'+esc(c.id)+'">'+esc(c.title)+(c.ready?'':' · 整理中')+'</button>').join('');}
function render(){prefs();$('#app').innerHTML='<aside class="sidebar"><div class="brand">2027 教资<small>科目二 · 教育知识与能力</small></div><nav class="nav">'+[['home','今日学习'],['review','复习与错题'],['saved','收藏与笔记'],['history','学习记录'],['settings','阅读设置']].map(([v,t])=>'<button data-route="'+v+'" class="'+(route===v?'selected':'')+'">'+t+'</button>').join('')+'</nav><div class="catalog">'+catalog.filter(c=>c.kind==='chapter').map(c=>'<details><summary>'+esc(c.title)+'</summary>'+catalog.filter(s=>s.parent_id===c.id).map(s=>'<div class="section-title">'+esc(s.title)+'</div>'+links(catalog.filter(p=>p.parent_id===s.id))).join('')+'</details>').join('')+'</div></aside><main class="main"><header class="topbar"><button class="mobile-menu" id="menu">目录</button><span class="title-label">我的学习空间<small id="sync">'+(pending.length?'待同步 '+pending.length+' 项':'已同步')+'</small></span><div class="top-actions"><span class="timer" id="timer">'+Math.floor((state.units[unit?.id]?.seconds||0)/60)+' 分钟</span><button id="timerBtn" '+(!unit?'disabled':'')+'>'+(timing?'暂停计时':'开始计时')+'</button><button id="out">退出</button></div></header><div class="body" id="body"></div></main>';
$('#out').onclick=logout;$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#timerBtn').onclick=()=>timing?stopTimer():startTimer();document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{await stopTimer();route=b.dataset.route;render();});document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.unit));if(route==='reader')reader();else if(route==='home')home();else if(route==='settings')settings();else listView();}
function home(){const d=M.day(now()),daily=state.days[d]||{seconds:0},plan=daily.plan,goal=plan?.goal||1500;let streak=0;for(let i=0;i<365;i++){const x=state.days[M.day(now()-i*86400000)];if(i===0&&(!x?.plan||x.seconds<x.plan.goal))continue;if(!x?.plan||x.seconds<x.plan.goal)break;streak++;}const n=new Date(now()+8*3600000).getUTCDay()||7,week=Array.from({length:n},(_,i)=>M.day(now()-(n-1-i)*86400000)),done=week.filter(k=>state.days[k]?.plan&&state.days[k].seconds>=state.days[k].plan.goal).length;$('#body').innerHTML='<div class="welcome"><div><div class="eyebrow">'+d+'</div><h1>今天，也向前一步。</h1><p class="muted">先完成今天的任务，再决定是否继续。</p></div><span class="tag">第一章样板建设中</span></div><div class="stats">'+[['今日学习',Math.floor(daily.seconds/60)+' 分钟'],['今日目标',goal/60+' 分钟'],['连续达标',streak+' 天'],['本周完成率',Math.round(done/week.length*100)+'%']].map(([a,b])=>'<div class="card stat"><small>'+a+'</small><strong>'+b+'</strong></div>').join('')+'</div><div class="dashboard-grid"><section class="card"><h2>今日任务</h2><div class="bar"><span style="width:'+Math.min(100,daily.seconds/goal*100)+'%"></span></div>'+(plan?.replanned?'<p class="warning">连续三天未达标，今天减至 10 分钟、一个知识点。历史记录保留。</p>':'')+(plan?.point_ids||[]).map(id=>{const c=catalog.find(c=>c.id===id);return c?'<div class="task"><div>'+esc(c.title)+'<p class="muted">'+esc(state.units[id]?.status||'未学习')+'</p></div><button data-open="'+id+'">开始学习</button></div>':'';}).join('')+(!plan?'<p class="empty">教材内容尚在整理，导入后生成今日任务。</p>':'')+'</section><section class="card"><h2>本周记录</h2><p class="muted">以北京时间和服务器计时为准，未完成记录不会补签或清除。</p>'+week.map(k=>'<div class="history-row"><span>'+k+'</span><span>'+(state.days[k]?.seconds>= (state.days[k]?.plan?.goal||Infinity)?'已达标':'未达标')+'</span></div>').join('')+'</section></div>';bindOpen();}
function bindOpen(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openUnit(b.dataset.open));}
async function openUnit(id){await stopTimer();unit=catalog.find(c=>c.id===id);if(!unit.ready){toast('该知识点尚在整理');return;}try{content=check(await db.from('tq_content').select('*').eq('id',id).single());route='reader';render();window.scrollTo(0,0);}catch(e){toast(e.message);}}
function reader(){const u=state.units[unit.id]||{status:'未学习',notes:[],highlights:[]};$('#body').innerHTML='<article class="reader"><div class="read-head"><div class="eyebrow">教材第 '+unit.page_start+'—'+unit.page_end+' 页</div><h1>'+esc(unit.title)+'</h1><div class="row"><button id="mode">切换冲刺模式</button><button id="scan">查看教材原页</button><button id="bookmark">'+(u.bookmark?'取消收藏':'收藏')+'</button><button id="highlight">高亮选中文字</button></div><div class="row"><label>学习状态 <select id="status">'+['未学习','学习中','模糊','已掌握'].map(x=>'<option '+(u.status===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><small>错误 '+(u.wrong||0)+' 次 · 自测正确率 '+(u.answers?Math.round(u.correct/u.answers*100):0)+'% · 下次复习 '+(u.due?M.day(u.due):'完成自测后安排')+'</small></div></div><p class="warning">'+esc(content.verification)+'。扫描原页是最高优先级依据；AI 辅助内容与教材分开。</p><section class="source-section"><h2>教材原文</h2><div class="source">'+content.blocks.map((b,i)=>'<div class="page-label">教材第 '+b.page+' 页 <button data-page="'+(b.pdf_page||b.page+4)+'">查看原页</button></div>'+(b.type==='scan'?'<div class="scan-block" data-scan="'+b.pdf_page+'">正在加载原页…</div>':'<details><summary>OCR 文字（待核对）</summary><p data-block="'+i+'">'+esc(b.text)+'</p></details>')).join('')+'</div></section>'+[['AI辅助解释','explanation','ai'],['考试重点（AI辅助）','exam','exam'],['易错点（AI辅助）','pitfalls','pitfalls']].map(([a,k,cl])=>'<section><h2>'+a+'</h2><div class="'+cl+'"><p>'+esc(content[k]||'待补充，当前请依据教材原页学习。')+'</p></div></section>').join('')+'<section><h2>个人笔记</h2><textarea id="note" aria-label="个人笔记" placeholder="写下自己的理解，每次保存保留一个版本">'+esc(u.notes?.at(-1)?.text||'')+'</textarea><button id="saveNote">保存笔记</button><details class="versions"><summary>历史版本（'+(u.notes?.length||0)+'）</summary>'+(u.notes||[]).slice().reverse().map(n=>'<p><small>'+esc(n.at)+'</small><br>'+esc(n.text)+'</p>').join('')+'</details></section><section><h2>自测题（AI辅助）</h2>'+content.questions.map((q,i)=>'<div class="question"><p>'+esc(q.prompt)+'</p><details><summary>查看参考答案</summary><p class="answer">'+esc(q.answer)+'</p></details><div class="row"><button data-answer="'+i+'" data-correct="true">答对了</button><button data-answer="'+i+'" data-correct="false">答错了</button></div></div>').join('')+(!content.questions.length?'<p>自测题待整理。</p>':'')+'</section></article>';
$('#mode').onclick=()=>{$('.reader').classList.toggle('sprint');$('#mode').textContent=$('.reader').classList.contains('sprint')?'切换教材模式':'切换冲刺模式';};$('#scan').onclick=()=>showPage(unit.page_start+4);$('#bookmark').onclick=async()=>{await record('bookmark',{value:!u.bookmark});reader();};$('#status').onchange=async e=>{await record('status',{value:e.target.value});toast('状态已保存');};$('#saveNote').onclick=async()=>{await record('note',{text:$('#note').value});toast('笔记已保存，旧版本保留');reader();};$('#highlight').onclick=async()=>{const sel=window.getSelection(),txt=sel.toString();if(!txt||!$('.source').contains(sel.anchorNode)){toast('请先选择教材原文中的文字');return;}await record('highlight',{text:txt});reader();};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(+b.dataset.page));document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=async()=>{await record('answer',{question_id:content.questions[+b.dataset.answer].id,correct:b.dataset.correct==='true'});toast('已记录，下次复习时间已更新');reader();});for(const el of document.querySelectorAll('[data-scan]'))loadScan(+el.dataset.scan,el);for(const p of document.querySelectorAll('[data-block]')){let text=p.textContent;for(const h of u.highlights||[]){if(text.includes(h)){p.innerHTML=esc(text).split(esc(h)).join('<mark>'+esc(h)+'</mark>');break;}}}}
async function loadScan(n,el){try{const p=check(await db.from('tq_pages').select('image_data').eq('pdf_page',n).single());const img=new Image();img.alt='教材扫描第 '+n+' 页';img.src=p.image_data;el.replaceChildren(img);}catch{el.textContent='原页暂未载入，请稍后重试。';}}
async function showPage(n){$('#pageControls').innerHTML='<button id="prevPage" '+(n<=unit.page_start+4?'disabled':'')+'>上一页</button><span>扫描 '+n+' / 教材 '+(n-4)+'</span><button id="nextPage" '+(n>=unit.page_end+4?'disabled':'')+'>下一页</button>';$('#prevPage').onclick=()=>showPage(n-1);$('#nextPage').onclick=()=>showPage(n+1);$('#pageImage').textContent='正在加载…';if(!$('#pages').open)$('#pages').showModal();await loadScan(n,$('#pageImage'));}
$('#closePages').onclick=()=>$('#pages').close();
function settings(){$('#body').innerHTML='<section class="card settings"><h1>阅读设置</h1><label>主题<select id="theme"><option value="light">浅色</option><option value="dark">深色</option></select></label><label>字体大小<input id="font" type="range" min="16" max="28" value="'+(state.settings.font||18)+'"></label><label>阅读宽度<input id="width" type="range" min="600" max="1100" step="20" value="'+(state.settings.width||780)+'"></label><p class="muted">设置会同步到其他设备。</p></section>';$('#theme').value=state.settings.theme||'light';for(const id of ['theme','font','width'])$('#'+id).onchange=async e=>{await record('settings',{[id]:id==='theme'?e.target.value:+e.target.value},null);prefs();};}
function listView(){if(route==='history'){$('#body').innerHTML='<section class="card"><h1>学习记录</h1>'+Object.entries(state.days).sort().reverse().map(([d,v])=>'<div class="history-row"><span>'+d+'</span><span>'+Math.floor(v.seconds/60)+' 分钟 · '+(v.plan&&v.seconds>=v.plan.goal?'已达标':'未达标')+'</span></div>').join('')+'</section>';return;}const rows=catalog.filter(c=>c.kind==='point'&&(route==='saved'?(state.units[c.id]?.bookmark||state.units[c.id]?.notes?.length):(state.units[c.id]?.lastCorrect===false||state.units[c.id]?.status==='模糊'||new Date(state.units[c.id]?.due).getTime()<=now())));$('#body').innerHTML='<section class="card"><h1>'+(route==='saved'?'收藏与笔记':'复习与错题')+'</h1>'+rows.map(c=>'<div class="task"><span>'+esc(c.title)+'</span><button data-open="'+c.id+'">打开</button></div>').join('')+(!rows.length?'<p class="empty">这里暂时没有记录。</p>':'')+'</section>';bindOpen();}
async function startTimer(){if(timing||timerBusy||!unit)return;timerBusy=true;try{await record('time',{action:'start',device});timing=true;timerHandle=setInterval(tick,20000);render();}catch(e){toast(e.message);}finally{timerBusy=false;}}
async function tick(){if(!timing||timerBusy)return;timerBusy=true;try{await record('time',{action:'tick',device});if($('#timer'))$('#timer').textContent=Math.floor((state.units[unit.id]?.seconds||0)/60)+' 分钟';}catch(e){clearInterval(timerHandle);timing=false;toast('计时连接中断，请重新开始');if($('#timerBtn'))$('#timerBtn').textContent='开始计时';}finally{timerBusy=false;}}
async function stopTimer(){if(!timing)return;clearInterval(timerHandle);timing=false;try{await record('time',{action:'stop',device});}catch(e){toast('计时已停止，未确认的时长不计入达标');}if($('#timerBtn'))$('#timerBtn').textContent='开始计时';}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTimer();else{sync();ensurePlan().catch(()=>{});}});window.addEventListener('online',sync);window.addEventListener('storage',e=>{if(user&&e.key?.startsWith('tq-event-'+user.id+'-'))sync();});setInterval(()=>{if(user&&!document.hidden)sync();},15000);boot();
